version: "3"
services:
  backend:
    build:
      context: ./qode-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./qode-challenge
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # mongodb:
  #   image: mongo
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
